In [1]:
import pandas as pd
import numpy as np
from patsy import dmatrices
import statsmodels.formula.api as sm
from statsmodels.datasets.longley import load
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
df = pd.DataFrame(load().exog, columns=['X1', 'X2', 'X3', 'X4', 'X5', 'X6'])
df['Y'] = load().endog

D:\Program Files\Miniconda3\envs\venv\lib\site-packages\statsmodels\datasets\utils.py:100: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  exog = np.column_stack(data[field] for field in exog_name)

In [3]:
df.head()

     X1        X2      X3      X4        X5      X6        Y
0  83.0  234289.0  2356.0  1590.0  107608.0  1947.0  60323.0
1  88.5  259426.0  2325.0  1456.0  108632.0  1948.0  61122.0
2  88.2  258054.0  3682.0  1616.0  109773.0  1949.0  60171.0
3  89.5  284599.0  3351.0  1650.0  110929.0  1950.0  61187.0
4  96.2  328975.0  2099.0  3099.0  112075.0  1951.0  63221.0

In [4]:
results = sm.ols(formula='Y~X1+X2+X3+X4+X5+X6', data=df).fit()

In [5]:
df_x = df.copy()
df

       X1        X2      X3      X4        X5      X6        Y
0    83.0  234289.0  2356.0  1590.0  107608.0  1947.0  60323.0
1    88.5  259426.0  2325.0  1456.0  108632.0  1948.0  61122.0
2    88.2  258054.0  3682.0  1616.0  109773.0  1949.0  60171.0
3    89.5  284599.0  3351.0  1650.0  110929.0  1950.0  61187.0
4    96.2  328975.0  2099.0  3099.0  112075.0  1951.0  63221.0
5    98.1  346999.0  1932.0  3594.0  113270.0  1952.0  63639.0
6    99.0  365385.0  1870.0  3547.0  115094.0  1953.0  64989.0
7   100.0  363112.0  3578.0  3350.0  116219.0  1954.0  63761.0
8   101.2  397469.0  2904.0  3048.0  117388.0  1955.0  66019.0
9   104.6  419180.0  2822.0  2857.0  118734.0  1956.0  67857.0
10  108.4  442769.0  2936.0  2798.0  120445.0  1957.0  68169.0
11  110.8  444546.0  4681.0  2637.0  121950.0  1958.0  66513.0
12  112.6  482704.0  3813.0  2552.0  123366.0  1959.0  68655.0
13  114.2  502601.0  3931.0  2514.0  125368.0  1960.0  69564.0
14  115.7  518173.0  4806.0  2572.0  127852.0  1961.0  69331.0
15  116.9  554894.0  4007.0  2827.0  130081.0  1962.0  70551.0

In [6]:
predicted_Y = results.predict(df_x)

In [7]:
predicted_Y.head()

0    60055.659970
1    61216.013942
2    60124.712832
3    61597.114622
4    62911.285409
dtype: float64

In [8]:
results.summary()

D:\Program Files\Miniconda3\envs\venv\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     330.3
Date:                Tue, 02 Jul 2019   Prob (F-statistic):           4.98e-10
Time:                        13:34:44   Log-Likelihood:                -109.62
No. Observations:                  16   AIC:                             233.2
Df Residuals:                       9   BIC:                             238.6
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.482e+06    8.9e+05     -3.911      0.004    -5.5e+06   -1.47e+06
X1            15.0619     84.915      0.177      0.863    -177.029     207.153
X2            -0.0358      0.033     -1.070      0.313      -0.112       0.040
X3            -2.0202      0.488     -4.136      0.003      -3.125      -0.915
X4            -1.0332      0.214     -4.822      0.001      -1.518      -0.549
X5            -0.0511      0.226     -0.226      0.826      -0.563       0.460
X6          1829.1515    455.478      4.016      0.003     798.788    2859.515
==============================================================================
Omnibus:                        0.749   Durbin-Watson:                   2.559
Prob(Omnibus):                  0.688   Jarque-Bera (JB):                0.684
Skew:                           0.420   Prob(JB):                        0.710
Kurtosis:                       2.434   Cond. No.                     4.86e+09
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.86e+09. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
vif = pd.DataFrame()

In [10]:
vif["VIF Factor"] = [variance_inflation_factor(df_x.values, i) for i in range(df_x.shape[1])]
vif["features"] = df_x.columns

In [11]:
vif.round(1)

   VIF Factor features
0     12633.4       X1
1     16002.6       X2
2       150.2       X3
3        56.8       X4
4    118012.1       X5
5    148172.2       X6
6     30315.0        Y